version:  '3'
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
    ports:
      - '33061:3306'
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000
    volumes:
    - './bin/:/usr/src/app/bin'
    - './config/:/usr/src/app/config'
    - './public/:/usr/src/app/public'
    - './src/:/usr/src/app/src'
    - './var/:/usr/src/app/var'
    - './vendor/:/usr/src/app/vendor'