# Useful commands
# php bin/console doctrine:mapping:info
# php bin/console doctrine:query:sql "SELECT * FROM pilot"
# php composar.php install

#index:
#    path: /
#    controller: App\Controller\DefaultController::index

helloResponse:
  path: /helloController
  controller: App\Controller\HelloController::helloAction

# Put the most restrictive function at the top
lockedNumber:
  path: /helloController/{number}
  controller: App\Controller\HelloController::lockedNumberAction
  # You need to put this to lock the type of parameter
  requirements:
    number: \d+

number:
  path: /helloController/{number}
  controller: App\Controller\HelloController::numberAction


putMethod:
  path: /put
  controller: App\Controller\HelloController::putAction
  methods: PUT
  # do 'curl -X PUT localhost:8000/put' in the root directory of the project to see if the method works

# USER Related

user:
  path: /user
  controller: App\Controller\UserController::userAction

userNew:
  path: /user/{lastName}/{firstName}
  controller: App\Controller\UserController::userNew

userList:
  path: /user/list
  controller: App\Controller\UserController::userList



# AIRPORT Related
airport:
  resource: './routes/airport.yaml'
  prefix: /airport

# FLIGHT Related
flight:
  resource: './routes/flight.yaml'
  prefix: /flight

# PILOT Related
pilot:
  resource: './routes/pilot.yaml'
  prefix: /pilot

# PLANE Related
plane:
  resource: './routes/plane.yaml'
  prefix: /plane
